/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.customerDAO;
import DAO.populatorDAO;
import Model.CustomerDetailsMode;
import Model.populatorModel;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Acer
 */
public class CustomerView extends javax.swing.JFrame {

    /**
     * Creates new form CustomerView
     */
    public CustomerView() {
        initComponents();
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DashHomeLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DashCustomerDetailsLabel = new javax.swing.JLabel();
        DashBorrowDetailsLabel = new javax.swing.JLabel();
        DashCustomerPageLabel = new javax.swing.JLabel();
        DashBorrowPageLabel = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        UpdateDetailsButton = new javax.swing.JButton();
        DeleteCustomerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(238, 696));

        DashHomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DashHomeLabel.setIcon(new FlatSVGIcon("homeicon.svg"));
        DashHomeLabel.setText("Home");
        DashHomeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashHomeLabelMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BooksPics/logo_small.png"))); // NOI18N

        DashCustomerDetailsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DashCustomerDetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DashCustomerDetailsLabel.setIcon(new FlatSVGIcon("customers1.svg"));
        DashCustomerDetailsLabel.setText("Customer Details");
        DashCustomerDetailsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashCustomerDetailsLabelMouseClicked(evt);
            }
        });

        DashBorrowDetailsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DashBorrowDetailsLabel.setIcon(new FlatSVGIcon("bookBorrowed1.svg"));
        DashBorrowDetailsLabel.setText("Borrow Details");
        DashBorrowDetailsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashBorrowDetailsLabelMouseClicked(evt);
            }
        });

        DashCustomerPageLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DashCustomerPageLabel.setIcon(new FlatSVGIcon("customerPage.svg"));
        DashCustomerPageLabel.setText("Customers Page");

        DashBorrowPageLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DashBorrowPageLabel.setIcon(new FlatSVGIcon("borrowPage.svg"));
        DashBorrowPageLabel.setText("Borrow Page");
        DashBorrowPageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashBorrowPageLabelMouseClicked(evt);
            }
        });

        LogoutButton.setBackground(new java.awt.Color(255, 153, 0));
        LogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setIcon(new FlatSVGIcon("logout.svg"));
        LogoutButton.setText("Log Out");
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DashBorrowDetailsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DashCustomerPageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DashCustomerDetailsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(DashHomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DashBorrowPageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(DashHomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(DashCustomerDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(DashCustomerPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(DashBorrowDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(DashBorrowPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Customer Name", "Contact Number", "Email", "Address", "Gender"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel10.setText("CUSTOMERS VIEW");

        UpdateDetailsButton.setBackground(new java.awt.Color(255, 153, 0));
        UpdateDetailsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateDetailsButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateDetailsButton.setText("Update Details");
        UpdateDetailsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateDetailsButtonMouseClicked(evt);
            }
        });
        UpdateDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDetailsButtonActionPerformed(evt);
            }
        });

        DeleteCustomerButton.setBackground(new java.awt.Color(255, 153, 0));
        DeleteCustomerButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteCustomerButton.setText("Delete Customer");
        DeleteCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCustomerButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setText("About");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel8.setText("Support");

        jLabel15.setIcon(new FlatSVGIcon("loginLogo.svg"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UpdateDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                        .addComponent(UpdateDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153)
                        .addComponent(DeleteCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(53, Short.MAX_VALUE))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCustomerButtonActionPerformed
//       
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        if (jTable1.getSelectedRowCount() == 1){
        populatorDAO pdd = new populatorDAO();
        
        pdd.deleteCustomer(Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString()));
                        
                        this.dispose();
                    
                        JOptionPane.showMessageDialog(this, "customer deleted successfully");
                        CustomerView ok = new CustomerView();
                        ok.setVisible(true);
                    } 
    }//GEN-LAST:event_DeleteCustomerButtonActionPerformed

    private void LogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseClicked
       this.dispose();
       LoginPage log = new LoginPage();
       log.setVisible(true);
    }//GEN-LAST:event_LogoutButtonMouseClicked

    private void DashHomeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashHomeLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        HomePage home = new HomePage();
        home.setVisible(true);
    }//GEN-LAST:event_DashHomeLabelMouseClicked

    private void DashCustomerDetailsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashCustomerDetailsLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        CustomerDetails cd = new CustomerDetails();
        cd.setVisible(true);
    }//GEN-LAST:event_DashCustomerDetailsLabelMouseClicked

    private void DashBorrowDetailsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashBorrowDetailsLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        BookingDetails bd = new BookingDetails();
        bd.setVisible(true);
    }//GEN-LAST:event_DashBorrowDetailsLabelMouseClicked

    private void DashBorrowPageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashBorrowPageLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        BooksView bv = new BooksView();
        bv.setVisible(true);
    }//GEN-LAST:event_DashBorrowPageLabelMouseClicked
    
    private void populate(){
        
         populatorDAO pd=new populatorDAO();
        List<populatorModel> CustomerList = pd.fetchCustomers();
        String[] columnNames={"Customer ID","Customer Name","C Number","Email","Address","Gender"};
        DefaultTableModel model = new DefaultTableModel(columnNames,0);
        for(populatorModel customers: CustomerList){
            Object[] rowData ={customers.id,customers.getName(),customers.getContact(),customers.getEmail(),customers.getAddress(),customers.getGender()};
            model.addRow(rowData);
        }
        jTable1.setModel(model);
    }
    private void UpdateDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDetailsButtonActionPerformed
//
        
        
    }//GEN-LAST:event_UpdateDetailsButtonActionPerformed

    private void UpdateDetailsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateDetailsButtonMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        if (jTable1.getSelectedRowCount() == 1) {
        CustomerDetailsMode a = new CustomerDetailsMode(jTable1.getModel().getValueAt(row, 1).toString(), jTable1.getModel().getValueAt(row,5).toString(),jTable1.getModel().getValueAt(row, 4).toString(),jTable1.getModel().getValueAt(row, 2).toString(),jTable1.getModel().getValueAt(row,3).toString());
        
        populatorDAO pdd = new populatorDAO();
        customerDAO cdd = new customerDAO();
        pdd.deleteCustomer(Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString()));
                        cdd.addCustomer(a);
                        this.dispose();
                    
                        JOptionPane.showMessageDialog(this, "customer updated successfully");
                        CustomerView ok = new CustomerView();
                        ok.setVisible(true);
                    } 

       
    
    }//GEN-LAST:event_UpdateDetailsButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DashBorrowDetailsLabel;
    private javax.swing.JLabel DashBorrowPageLabel;
    private javax.swing.JLabel DashCustomerDetailsLabel;
    private javax.swing.JLabel DashCustomerPageLabel;
    private javax.swing.JLabel DashHomeLabel;
    private javax.swing.JButton DeleteCustomerButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton UpdateDetailsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
